---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: default